AcerCms.UI/Areas/Admin/Controllers/HaberController.cs
using System;
using System.Data.Entity.Validation;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using AcerCms.Dal;
using AcerCms.Dal.Enities;
using AcerCms.UI.Areas.Admin.Models;
using AcerCms.UI.Areas.Admin.ModelServices;
using Microsoft.AspNet.Identity;


namespace AcerCms.UI.Areas.Admin.Controllers
{
    [Authorize]
    public class HaberController : BaseController
    {
        // GET: Admin/Haber
        [OutputCache(CacheProfile = "Cache1Hour")]
        public ActionResult Index(int page = 1)
        {
            var model = HaberModelService.GetNews(page);           
            return View(model);
        }

        //[NonAction]
        public string AddSomeNews()
        {
            var userId = User.Identity.GetUserId();
            var news = new News[]
            {
                new News() {  Title = "1. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "2. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "3. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "4. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "5. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "6. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "7. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "8. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "9. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0, PersonId = userId},
                new News() {  Title = "10. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId},
                new News() {  Title = "11. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId},
                new News() {  Title = "12. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId},
                new News() {  Title = "13. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId},
                new News() {  Title = "14. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId},
                new News() {  Title = "15. haber",  Content = "skj hkjahskjhkjhksjd", ShortDescription = "hjda gfjhgj", UpdateDate = DateTime.Now, ViewCount = 0,PersonId = userId}
            };

            using (var db = new ApplicationDbContext())
            {
                db.News.AddRange(news);
                db.SaveChanges();
            }
            return null;
        }

        public ActionResult YeniHaber()
        {
            //var news = new News();
            /*
             * Var 
             * Object
             * Dynamic
             * */

            var model = new NewsViewModel()
            {
                isDeleted = true
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult YeniHaber(News news, HttpPostedFileBase file)
        {            
            string fileName = Path.GetFileName(file.FileName);
            file.SaveAs(Server.MapPath("~/Content/Uploads/" + fileName));
            try
            {
                using (var db = new ApplicationDbContext())
                {
                    var yeniHaber = new News
                    {
                        Title = news.Title,
                        ShortDescription = news.ShortDescription,
                        Content = news.Content,
                        UpdateDate = DateTime.Today,
                        IsDeleted = news.IsDeleted,
                        ViewCount = news.ViewCount,
                        Picture =  new Picture
                        {
                            
                            Title = news.Title,
                            Description = news.Title,
                            Path = "/Content/Admin/",
                            FileName = fileName                                 
                        }
                    };
                   
                    db.News.Add(yeniHaber);
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Response.Write(string.Format("Entity türü \"{0}\" şu hatalara sahip \"{1}\" Geçerlilik hataları:", eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Response.Write(string.Format("- Özellik: \"{0}\", Hata: \"{1}\"", ve.PropertyName, ve.ErrorMessage));
                    }
                    Response.End();
                }
            }

            return RedirectToAction("YeniHaber");
        }
    }
}

AcerCms.UI/Areas/Admin/Views/Haber/Index.cshtml
@model IEnumerable<AcerCms.Dal.Enities.News>
@{
    ViewBag.Title = "Haberler";
}

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Yeni</button>
        </div>
    </div>
</div>


@if (Model.Any())
{
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Title</th>
            <th>UpdateDate</th>
            <th>ViewCount</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var news in Model)
        {
            <tr>
                <td>@news.Title</td>
                <td>@news.UpdateDate</td>
                <td>@news.ViewCount</td>
                <td>
                    <a href="#">Düzenle</a>
                    <a href="#">Sil</a>
                </td>
            </tr>
        }
        </tbody>

        <tfoot>
        <tr>
            <td colspan="4">
                @Html.Pagination()                
            </td>
        </tr>        
        </tfoot>
    </table>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Dikkat!</strong> Henüz Haber Eklenmemiş.
            </div>
        </div>
    </div>
}    

AcerCms.UI/Areas/Admin/Views/Haber/YeniHaber.cshtml
@using AcerCms.UI.Areas.Admin.Models
@model AcerCms.UI.Areas.Admin.Models.NewsViewModel
@{
    ViewBag.Title = "Yeni Haber";    
}

<div id="loading" style="display: none;">Lütfen Bekleyiniz...</div>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Yeni Haber</h3>
                </div>

                @using (Ajax.BeginForm("YeniHaber", "Haber", new AjaxOptions()
                {
                    HttpMethod = "post",
                    InsertionMode = InsertionMode.Replace,
                    LoadingElementId = "loading"
                }, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })


                    
                    
                    <div class="box-body">

                        
                        @Html.DisplayFor(m=> m.isDeleted, "CheckBox")

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "control-label" })
                            @Html.EditorFor(model => model.Title)
                            @Html.ValidationMessageFor(model=> model.Title)
                        </div>*@

                        @Html.EditorFor(m=> m.Title, "FormGroup")

                        @*<div class="form-group">
                            <label for="exampleInputPassword1">Kısa Açıklama</label>                           
                            @Html.TextBoxFor(model => model.ShortDescription, new { @class = "form-control", @placeholder = "Kısa Açıklama" })
                        </div>*@
                        @Html.EditorFor(m => m.ShortDescription, "FormGroup")

                        @*<div class="form-group">
                            <label for="exampleInputPassword1">İçerik</label>
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @placeholder = "İçerik", @rows = "5" })
                        </div>*@

                        @Html.EditorFor(m=> m.Content, "FormGroupTextArea")

                        <div class="form-group">
                            <label for="exampleInputPassword1">Görüntülenme Sayısı</label>
                            @Html.TextBoxFor(model => model.ViewCount, new { @class = "form-control", @placeholder = "" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputFile">Resim</label>
                            <input type="file" id="haberResim" name="file">
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}